textdata_dirname: /home/bekki/dropbox/Public/MyData/bccwjcore
jumanlog_dirname: /home/bekki/program/hasktorch-tools/app/juman-lstm-language-model/jumanlog
dic_filename: /home/bekki/program/hasktorch-tools/app/juman-lstm-language-model/dic.yaml
